export const BIBLE_BOOKS_FALLBACK = [
  { abbrev: { pt: "gn" }, name: "Gênesis", chapters: 50, testament: "VT" },
  { abbrev: { pt: "ex" }, name: "Êxodo", chapters: 40, testament: "VT" },
  { abbrev: { pt: "lv" }, name: "Levítico", chapters: 27, testament: "VT" },
  { abbrev: { pt: "nm" }, name: "Números", chapters: 36, testament: "VT" },
  { abbrev: { pt: "dt" }, name: "Deuteronômio", chapters: 34, testament: "VT" },
  { abbrev: { pt: "js" }, name: "Josué", chapters: 24, testament: "VT" },
  { abbrev: { pt: "jz" }, name: "Juízes", chapters: 21, testament: "VT" },
  { abbrev: { pt: "rt" }, name: "Rute", chapters: 4, testament: "VT" },
  { abbrev: { pt: "1sm" }, name: "1 Samuel", chapters: 31, testament: "VT" },
  { abbrev: { pt: "2sm" }, name: "2 Samuel", chapters: 24, testament: "VT" },
  { abbrev: { pt: "1rs" }, name: "1 Reis", chapters: 22, testament: "VT" },
  { abbrev: { pt: "2rs" }, name: "2 Reis", chapters: 25, testament: "VT" },
  { abbrev: { pt: "1cr" }, name: "1 Crônicas", chapters: 29, testament: "VT" },
  { abbrev: { pt: "2cr" }, name: "2 Crônicas", chapters: 36, testament: "VT" },
  { abbrev: { pt: "ed" }, name: "Esdras", chapters: 10, testament: "VT" },
  { abbrev: { pt: "ne" }, name: "Neemias", chapters: 13, testament: "VT" },
  { abbrev: { pt: "et" }, name: "Ester", chapters: 10, testament: "VT" },
  { abbrev: { pt: "job" }, name: "Jó", chapters: 42, testament: "VT" },
  { abbrev: { pt: "sl" }, name: "Salmos", chapters: 150, testament: "VT" },
  { abbrev: { pt: "pv" }, name: "Provérbios", chapters: 31, testament: "VT" },
  { abbrev: { pt: "ec" }, name: "Eclesiastes", chapters: 12, testament: "VT" },
  { abbrev: { pt: "ct" }, name: "Cantares", chapters: 8, testament: "VT" },
  { abbrev: { pt: "is" }, name: "Isaías", chapters: 66, testament: "VT" },
  { abbrev: { pt: "jr" }, name: "Jeremias", chapters: 52, testament: "VT" },
  { abbrev: { pt: "lm" }, name: "Lamentações", chapters: 5, testament: "VT" },
  { abbrev: { pt: "ez" }, name: "Ezequiel", chapters: 48, testament: "VT" },
  { abbrev: { pt: "dn" }, name: "Daniel", chapters: 12, testament: "VT" },
  { abbrev: { pt: "os" }, name: "Oséias", chapters: 14, testament: "VT" },
  { abbrev: { pt: "jl" }, name: "Joel", chapters: 3, testament: "VT" },
  { abbrev: { pt: "am" }, name: "Amós", chapters: 9, testament: "VT" },
  { abbrev: { pt: "ob" }, name: "Obadias", chapters: 1, testament: "VT" },
  { abbrev: { pt: "jn" }, name: "Jonas", chapters: 4, testament: "VT" },
  { abbrev: { pt: "mq" }, name: "Miquéias", chapters: 7, testament: "VT" },
  { abbrev: { pt: "na" }, name: "Naum", chapters: 3, testament: "VT" },
  { abbrev: { pt: "hc" }, name: "Habacuque", chapters: 3, testament: "VT" },
  { abbrev: { pt: "sf" }, name: "Sofonias", chapters: 3, testament: "VT" },
  { abbrev: { pt: "ag" }, name: "Ageu", chapters: 2, testament: "VT" },
  { abbrev: { pt: "zc" }, name: "Zacarias", chapters: 14, testament: "VT" },
  { abbrev: { pt: "ml" }, name: "Malaquias", chapters: 4, testament: "VT" },
  { abbrev: { pt: "mt" }, name: "Mateus", chapters: 28, testament: "NT" },
  { abbrev: { pt: "mc" }, name: "Marcos", chapters: 16, testament: "NT" },
  { abbrev: { pt: "lc" }, name: "Lucas", chapters: 24, testament: "NT" },
  { abbrev: { pt: "jo" }, name: "João", chapters: 21, testament: "NT" },
  { abbrev: { pt: "at" }, name: "Atos", chapters: 28, testament: "NT" },
  { abbrev: { pt: "rm" }, name: "Romanos", chapters: 16, testament: "NT" },
  { abbrev: { pt: "1co" }, name: "1 Coríntios", chapters: 16, testament: "NT" },
  { abbrev: { pt: "2co" }, name: "2 Coríntios", chapters: 13, testament: "NT" },
  { abbrev: { pt: "gl" }, name: "Gálatas", chapters: 6, testament: "NT" },
  { abbrev: { pt: "ef" }, name: "Efésios", chapters: 6, testament: "NT" },
  { abbrev: { pt: "fp" }, name: "Filipenses", chapters: 4, testament: "NT" },
  { abbrev: { pt: "cl" }, name: "Colossenses", chapters: 4, testament: "NT" },
  { abbrev: { pt: "1ts" }, name: "1 Tessalonicenses", chapters: 5, testament: "NT" },
  { abbrev: { pt: "2ts" }, name: "2 Tessalonicenses", chapters: 3, testament: "NT" },
  { abbrev: { pt: "1tm" }, name: "1 Timóteo", chapters: 6, testament: "NT" },
  { abbrev: { pt: "2tm" }, name: "2 Timóteo", chapters: 4, testament: "NT" },
  { abbrev: { pt: "tt" }, name: "Tito", chapters: 3, testament: "NT" },
  { abbrev: { pt: "fm" }, name: "Filemom", chapters: 1, testament: "NT" },
  { abbrev: { pt: "hb" }, name: "Hebreus", chapters: 13, testament: "NT" },
  { abbrev: { pt: "tg" }, name: "Tiago", chapters: 5, testament: "NT" },
  { abbrev: { pt: "1pe" }, name: "1 Pedro", chapters: 5, testament: "NT" },
  { abbrev: { pt: "2pe" }, name: "2 Pedro", chapters: 3, testament: "NT" },
  { abbrev: { pt: "1jo" }, name: "1 João", chapters: 5, testament: "NT" },
  { abbrev: { pt: "2jo" }, name: "2 João", chapters: 1, testament: "NT" },
  { abbrev: { pt: "3jo" }, name: "3 João", chapters: 1, testament: "NT" },
  { abbrev: { pt: "jd" }, name: "Judas", chapters: 1, testament: "NT" },
  { abbrev: { pt: "ap" }, name: "Apocalipse", chapters: 22, testament: "NT" },
];
