import { InsertAchievement } from "@shared/schema";

export const achievements: InsertAchievement[] = [
  {
    name: "Primeira Leitura",
    description: "Complete sua primeira leitura de capítulo",
    icon: "book-open",
    category: "leitura",
    xpReward: 10,
    requirement: "Ler 1 capítulo",
  },
  {
    name: "Leitor Dedicado",
    description: "Leia 10 capítulos",
    icon: "book",
    category: "leitura",
    xpReward: 50,
    requirement: "Ler 10 capítulos",
  },
  {
    name: "Estudioso da Palavra",
    description: "Leia 50 capítulos",
    icon: "book-marked",
    category: "leitura",
    xpReward: 250,
    requirement: "Ler 50 capítulos",
  },
  {
    name: "Mestre das Escrituras",
    description: "Leia 100 capítulos",
    icon: "graduation-cap",
    category: "leitura",
    xpReward: 500,
    requirement: "Ler 100 capítulos",
  },
  {
    name: "Sequência de 7 Dias",
    description: "Mantenha uma sequência de leitura de 7 dias consecutivos",
    icon: "flame",
    category: "streak",
    xpReward: 100,
    requirement: "Streak de 7 dias",
  },
  {
    name: "Sequência de 30 Dias",
    description: "Mantenha uma sequência de leitura de 30 dias consecutivos",
    icon: "trophy",
    category: "streak",
    xpReward: 500,
    requirement: "Streak de 30 dias",
  },
  {
    name: "Sequência de 100 Dias",
    description: "Mantenha uma sequência de leitura de 100 dias consecutivos",
    icon: "crown",
    category: "streak",
    xpReward: 2000,
    requirement: "Streak de 100 dias",
  },
  {
    name: "Primeiro Plano Completo",
    description: "Complete seu primeiro plano de leitura",
    icon: "check-circle",
    category: "planos",
    xpReward: 100,
    requirement: "Completar 1 plano",
  },
  {
    name: "Planejador Consistente",
    description: "Complete 5 planos de leitura",
    icon: "list-checks",
    category: "planos",
    xpReward: 500,
    requirement: "Completar 5 planos",
  },
  {
    name: "Guerreiro de Oração",
    description: "Registre 10 orações no diário de oração",
    icon: "heart",
    category: "oração",
    xpReward: 50,
    requirement: "Registrar 10 orações",
  },
  {
    name: "Intercessor Fiel",
    description: "Registre 50 orações no diário de oração",
    icon: "heart-handshake",
    category: "oração",
    xpReward: 250,
    requirement: "Registrar 50 orações",
  },
  {
    name: "Anotador Iniciante",
    description: "Crie sua primeira nota de estudo",
    icon: "pencil",
    category: "notas",
    xpReward: 20,
    requirement: "Criar 1 nota",
  },
  {
    name: "Pesquisador das Escrituras",
    description: "Crie 25 notas de estudo",
    icon: "notebook-pen",
    category: "notas",
    xpReward: 150,
    requirement: "Criar 25 notas",
  },
  {
    name: "Marcador de Versículos",
    description: "Destaque 10 versículos",
    icon: "highlighter",
    category: "destaques",
    xpReward: 30,
    requirement: "Destacar 10 versículos",
  },
  {
    name: "Colecionador de Tesouros",
    description: "Destaque 50 versículos",
    icon: "gem",
    category: "destaques",
    xpReward: 200,
    requirement: "Destacar 50 versículos",
  },
  {
    name: "Membro da Comunidade",
    description: "Compartilhe sua primeira reflexão com a comunidade",
    icon: "users",
    category: "comunidade",
    xpReward: 50,
    requirement: "Criar 1 post",
  },
  {
    name: "Influenciador Espiritual",
    description: "Compartilhe 10 reflexões com a comunidade",
    icon: "share-2",
    category: "comunidade",
    xpReward: 300,
    requirement: "Criar 10 posts",
  },
  {
    name: "Explorador Completo",
    description: "Experimente todas as funcionalidades do app (leitura, oração, notas, planos, comunidade)",
    icon: "compass",
    category: "exploração",
    xpReward: 200,
    requirement: "Usar todas as funcionalidades",
  },
];
