import type { InsertDailyVerse } from "@shared/schema";

export const seedDailyVerses: InsertDailyVerse[] = [
  {
    dayOfYear: 1,
    book: "João",
    chapter: 3,
    verseNumber: 16,
    version: "nvi",
    text: "Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna.",
    reference: "João 3:16",
    theme: "amor",
  },
  {
    dayOfYear: 2,
    book: "Filipenses",
    chapter: 4,
    verseNumber: 13,
    version: "nvi",
    text: "Tudo posso naquele que me fortalece.",
    reference: "Filipenses 4:13",
    theme: "força",
  },
  {
    dayOfYear: 3,
    book: "Salmos",
    chapter: 23,
    verseNumber: 1,
    version: "nvi",
    text: "O Senhor é o meu pastor; nada me faltará.",
    reference: "Salmos 23:1",
    theme: "confiança",
  },
  {
    dayOfYear: 4,
    book: "Provérbios",
    chapter: 3,
    verseNumber: 5,
    version: "nvi",
    text: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento.",
    reference: "Provérbios 3:5",
    theme: "confiança",
  },
  {
    dayOfYear: 5,
    book: "Romanos",
    chapter: 8,
    verseNumber: 28,
    version: "nvi",
    text: "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.",
    reference: "Romanos 8:28",
    theme: "esperança",
  },
  {
    dayOfYear: 6,
    book: "Jeremias",
    chapter: 29,
    verseNumber: 11,
    version: "nvi",
    text: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar a vocês esperança e um futuro.",
    reference: "Jeremias 29:11",
    theme: "esperança",
  },
  {
    dayOfYear: 7,
    book: "Isaías",
    chapter: 40,
    verseNumber: 31,
    version: "nvi",
    text: "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.",
    reference: "Isaías 40:31",
    theme: "força",
  },
  {
    dayOfYear: 8,
    book: "Mateus",
    chapter: 11,
    verseNumber: 28,
    version: "nvi",
    text: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu darei descanso a vocês.",
    reference: "Mateus 11:28",
    theme: "descanso",
  },
  {
    dayOfYear: 9,
    book: "Salmos",
    chapter: 46,
    verseNumber: 1,
    version: "nvi",
    text: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.",
    reference: "Salmos 46:1",
    theme: "proteção",
  },
  {
    dayOfYear: 10,
    book: "Josué",
    chapter: 1,
    verseNumber: 9,
    version: "nvi",
    text: "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore, nem se desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
    reference: "Josué 1:9",
    theme: "coragem",
  },
  {
    dayOfYear: 11,
    book: "1 Coríntios",
    chapter: 13,
    verseNumber: 4,
    version: "nvi",
    text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.",
    reference: "1 Coríntios 13:4",
    theme: "amor",
  },
  {
    dayOfYear: 12,
    book: "Salmos",
    chapter: 119,
    verseNumber: 105,
    version: "nvi",
    text: "Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.",
    reference: "Salmos 119:105",
    theme: "orientação",
  },
  {
    dayOfYear: 13,
    book: "Gálatas",
    chapter: 5,
    verseNumber: 22,
    version: "nvi",
    text: "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade.",
    reference: "Gálatas 5:22",
    theme: "espiritualidade",
  },
  {
    dayOfYear: 14,
    book: "Efésios",
    chapter: 2,
    verseNumber: 8,
    version: "nvi",
    text: "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus.",
    reference: "Efésios 2:8",
    theme: "graça",
  },
  {
    dayOfYear: 15,
    book: "Colossenses",
    chapter: 3,
    verseNumber: 23,
    version: "nvi",
    text: "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens.",
    reference: "Colossenses 3:23",
    theme: "propósito",
  },
  {
    dayOfYear: 16,
    book: "Hebreus",
    chapter: 11,
    verseNumber: 1,
    version: "nvi",
    text: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.",
    reference: "Hebreus 11:1",
    theme: "fé",
  },
  {
    dayOfYear: 17,
    book: "Tiago",
    chapter: 1,
    verseNumber: 2,
    version: "nvi",
    text: "Meus irmãos, considerem motivo de grande alegria o fato de passarem por diversas provações.",
    reference: "Tiago 1:2",
    theme: "alegria",
  },
  {
    dayOfYear: 18,
    book: "1 Pedro",
    chapter: 5,
    verseNumber: 7,
    version: "nvi",
    text: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.",
    reference: "1 Pedro 5:7",
    theme: "paz",
  },
  {
    dayOfYear: 19,
    book: "2 Timóteo",
    chapter: 1,
    verseNumber: 7,
    version: "nvi",
    text: "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.",
    reference: "2 Timóteo 1:7",
    theme: "coragem",
  },
  {
    dayOfYear: 20,
    book: "Salmos",
    chapter: 27,
    verseNumber: 1,
    version: "nvi",
    text: "O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é o meu forte refúgio; de quem terei medo?",
    reference: "Salmos 27:1",
    theme: "proteção",
  },
  {
    dayOfYear: 21,
    book: "Mateus",
    chapter: 6,
    verseNumber: 33,
    version: "nvi",
    text: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas serão acrescentadas a vocês.",
    reference: "Mateus 6:33",
    theme: "prioridades",
  },
  {
    dayOfYear: 22,
    book: "Romanos",
    chapter: 12,
    verseNumber: 2,
    version: "nvi",
    text: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.",
    reference: "Romanos 12:2",
    theme: "transformação",
  },
  {
    dayOfYear: 23,
    book: "Provérbios",
    chapter: 16,
    verseNumber: 3,
    version: "nvi",
    text: "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.",
    reference: "Provérbios 16:3",
    theme: "sucesso",
  },
  {
    dayOfYear: 24,
    book: "Isaías",
    chapter: 41,
    verseNumber: 10,
    version: "nvi",
    text: "Não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa.",
    reference: "Isaías 41:10",
    theme: "coragem",
  },
  {
    dayOfYear: 25,
    book: "João",
    chapter: 14,
    verseNumber: 6,
    version: "nvi",
    text: "Respondeu Jesus: 'Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim.'",
    reference: "João 14:6",
    theme: "salvação",
  },
  {
    dayOfYear: 26,
    book: "Salmos",
    chapter: 91,
    verseNumber: 1,
    version: "nvi",
    text: "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso.",
    reference: "Salmos 91:1",
    theme: "proteção",
  },
  {
    dayOfYear: 27,
    book: "Eclesiastes",
    chapter: 3,
    verseNumber: 1,
    version: "nvi",
    text: "Há um tempo certo para tudo. Há um tempo certo para cada propósito debaixo do céu.",
    reference: "Eclesiastes 3:1",
    theme: "tempo",
  },
  {
    dayOfYear: 28,
    book: "Atos",
    chapter: 1,
    verseNumber: 8,
    version: "nvi",
    text: "Mas receberão poder quando o Espírito Santo descer sobre vocês, e serão minhas testemunhas em Jerusalém, em toda a Judeia e Samaria, e até os confins da terra.",
    reference: "Atos 1:8",
    theme: "poder",
  },
  {
    dayOfYear: 29,
    book: "Apocalipse",
    chapter: 3,
    verseNumber: 20,
    version: "nvi",
    text: "Eis que estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei e cearei com ele, e ele comigo.",
    reference: "Apocalipse 3:20",
    theme: "comunhão",
  },
  {
    dayOfYear: 30,
    book: "Miquéias",
    chapter: 6,
    verseNumber: 8,
    version: "nvi",
    text: "Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige: pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus.",
    reference: "Miquéias 6:8",
    theme: "justiça",
  },
];
